apiVersion: v1
kind: Service
metadata:
  name: grafana-public
spec:
  type: LoadBalancer
  selector:
    app: grafana-public
  ports:
  - name: grafana
    port: 80
    targetPort: 3000
    protocol: TCP
