apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-analytics-test

secretGenerator:
- name: pgo-azure-creds
  files:
  - azure.conf

generatorOptions:
  disableNameSuffixHash: true

resources:
- postgres.yaml
