apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-analytics-test

resources:
- pgadmin.yaml

secretGenerator:
- name: pgadmin-password-secret
  literals:
  - rhino-password=pgadmin
  type: Opaque

generatorOptions:
  disableNameSuffixHash: true
